### ISSUE TITLE
Filter data in #66

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/rivers-stream#68]
- alteration should be displayed IF 15 years of gage data is available 

See #66

**Comment by kklausmeyer** [comment]
Actually, Julie and I decided to provide the alteration data if there are >= 5 years of data.  However, in the web app, the alteration will display as grey if observed years is <15, instead of red to show it is altered.  So no filtering is needed.  I suggest we close this issue because all records with <5 years have already been removed.
